### ISSUE TITLE
falta composer.json

### ISSUE THREAD

**Issue by pedroreartes** [HermesMartins/crud-laravel-5.4-angularjs-1.6.3#3]
Hola amigo. 
composer install:   Composer could not find a composer.json file
Gracias!!

**Comment by HermesMartins** [comment]
Hola pedro! 

Tienes que primero acceder la carpeta backend y entonces hacer el 'composer install'.

Saludos

**Comment by pedroreartes** [comment]
Excelente Hermes!
muchas gracias!!!!!!


2017-09-12 23:04 GMT-03:00 Hermes Davy Martins <notifications@github.com>:
